# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 05:12
from __future__ import unicode_literals

import apps.loginRegister.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, validators=[apps.loginRegister.models.validatePassword]),
        ),
    ]
